name: %%IMAGE%%

description: "Integration testing"

base-image: %%REGISTRY%%/%%IMAGE%%

image-version: latest

alt-tags: 
  - integrationtest

modules:
  - type: files
    files:
      - source: system  
        destination: /
  - type: script
    scripts:
    - enableserivces.sh